name = "happybirth-app"
account_id = "f36929138c42b84cddc0584aae36e0f2"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Powiązanie z bazą Cloudflare D1
[[d1_databases]]
binding = "DB"
database_name = "happybirth-db"
database_id = "96bcdac7-6ad6-4ef7-91ff-93cf0f901cbf"
migrations_dir = "migrations"
