import { Stage, Lesson, MedicineCabinetItem } from './types';

export const CLOUDFLARE_CUSTOMER_DOMAIN = "customer-6d9sm694eja9tkvc.cloudflarestream.com";

export const stages: Stage[] = [
  {
    "id": "stage-01",
    "num": "01",
    "slug": "zanim",
    "title": "Zanim",
    "subtitle": "Świadome przygotowanie i fundament",
    "weeks": "Przed ciążą / Planowanie",
    "color": "#867A72",
    "accentBg": "#F0EDE9",
    "description": "Przygotowanie ciała i głowy, badania wstępne, kalkulator tygodnia i pierwsze decyzje."
  },
  {
    "id": "stage-02",
    "num": "02",
    "slug": "dwie-kreski",
    "title": "Dwie kreski",
    "subtitle": "I Trymestr – początek i wielka zmiana",
    "weeks": "Tydzień 1 – 14",
    "color": "#15803d",
    "accentBg": "#DCFCE7",
    "description": "Jak liczyć wiek ciąży, radzenie sobie z mdłościami, aplikacje, wybór lekarza i przełamywanie mitów."
  },
  {
    "id": "stage-03",
    "num": "03",
    "slug": "wreszcie-lepiej",
    "title": "Wreszcie lepiej",
    "subtitle": "II & III Trymestr – zmysły, ciało i profilaktyka",
    "weeks": "Tydzień 15 – 32",
    "color": "#b45309",
    "accentBg": "#FEF3C7",
    "description": "Ruchy dziecka, kalendarz badań, higiena intymna, bezpieczny sen na lewym boku i fizjoterapia kręgosłupa."
  },
  {
    "id": "stage-04",
    "num": "04",
    "slug": "torba-spakowana",
    "title": "Torba spakowana",
    "subtitle": "Wyprawka, kącik malucha i domowa apteczka",
    "weeks": "Tydzień 30 – 37",
    "color": "#0369a1",
    "accentBg": "#E0F2FE",
    "description": "Wybór bezpiecznego wózka i fotelika, materac do łóżeczka, apteczka minimum i lista ubranek na start."
  },
  {
    "id": "stage-05",
    "num": "05",
    "slug": "zaczelo-sie",
    "title": "Zaczęło się",
    "subtitle": "Poród naturalny – akcja, oddech i ruch",
    "weeks": "Tydzień 38 – 42",
    "color": "#EC008C",
    "accentBg": "#FCE7F3",
    "description": "Gdy odejdą wody, pozycje wertykalne, masaż krzyżowy z partnerem, chusta Rebozo i pakowanie do szpitala."
  },
  {
    "id": "stage-06",
    "num": "06",
    "slug": "plan-b",
    "title": "Plan B",
    "subtitle": "Cesarskie cięcie, znieczulenie i nieprzewidziane sytuacje",
    "weeks": "Poród / Godzina Zero",
    "color": "#7e22ce",
    "accentBg": "#F3E8FF",
    "description": "Wszystko o znieczuleniu ZZO, gazie rozweselającym, cięciu cesarskim i radzeniu sobie z kryzysem 7 cm."
  },
  {
    "id": "stage-07",
    "num": "07",
    "slug": "pierwsza-noc",
    "title": "Pierwsza noc w domu",
    "subtitle": "Połóg – regeneracja, emocje i powrót do sił",
    "weeks": "1 – 6 tydzień po porodzie",
    "color": "#be185d",
    "accentBg": "#FCE7F3",
    "description": "Pielęgnacja rany po cc i nacięciu, fizjologia połogu, Baby Blues, ćwiczenia dna miednicy i szczere historie mam."
  },
  {
    "id": "stage-08",
    "num": "08",
    "slug": "karmienie",
    "title": "Karmienie",
    "subtitle": "Laktacja bez bólu – technika i wsparcie",
    "weeks": "Od 1. doby życia",
    "color": "#0e7490",
    "accentBg": "#CFFAFE",
    "description": "Pozycje klasyczne i spod pachy, nawał pokarmowy, bolesne brodawki, dobór laktatora i łagodzenie kolek."
  },
  {
    "id": "stage-09",
    "num": "09",
    "slug": "nie-spi",
    "title": "Nie śpi",
    "subtitle": "Noworodek – kąpiel, bezpieczeństwo i pierwsza pomoc",
    "weeks": "1 – 12 miesiąc życia",
    "color": "#4338ca",
    "accentBg": "#E0E7FF",
    "description": "Skala Apgar, profilaktyka SIDS, RKO niemowlaka, instruktaż kąpieli, stany przejściowe i szczepienia."
  }
];

export const lessons: Lesson[] = [
  {
    "id": "lekcja-01",
    "lessonNumber": 1,
    "filmNumber": 1,
    "title": "I Trymestr – Początek nowego życia i pierwsze tygodnie",
    "description": "Dowiesz się, jak prawidłowo liczyć wiek ciąży od ostatniej miesiączki i co dzieje się w Twoim ciele od zapłodnienia do 14. tygodnia. Poznasz sposoby na poranne mdłości (częste, małe posiłki) i dowiesz się, dlaczego od razu warto zrezygnować z używek.",
    "stageId": "stage-02",
    "stageTitle": "Dwie kreski",
    "stageColor": "#15803d",
    "cloudflareUid": "f8d8d8f24b917a32961efea785c9324b",
    "durationSeconds": 333,
    "durationFormatted": "5:33",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/f8d8d8f24b917a32961efea785c9324b/thumbnails/thumbnail.jpg",
    "isFreePreview": true,
    "attachments": [
      {
        "id": "att-1-1",
        "name": "Karta Pracy · Lekcja 1",
        "type": "pdf",
        "size": "1.4 MB"
      }
    ]
  },
  {
    "id": "lekcja-02",
    "lessonNumber": 2,
    "filmNumber": 2,
    "title": "II Trymestr – Czas rozwoju zmysłów i pierwszych ruchów",
    "description": "Odkryjesz, jak rozwija się słuch i smak Twojego dziecka między 15. a 28. tygodniem oraz kiedy pojawiają się włoski i paznokcie. Dowiesz się, jak radzić sobie z zaparciami (otręby, woda) oraz dlaczego suplementacja żelaza i kwasów Omega-3 jest teraz kluczowa.",
    "stageId": "stage-02",
    "stageTitle": "Dwie kreski",
    "stageColor": "#15803d",
    "cloudflareUid": "4bc39467fbba88462fa0912a81503fb3",
    "durationSeconds": 156,
    "durationFormatted": "2:36",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/4bc39467fbba88462fa0912a81503fb3/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-03",
    "lessonNumber": 3,
    "filmNumber": 3,
    "title": "III Trymestr – Wielkie odliczanie do narodzin",
    "description": "Przygotujesz się na finisz (tygodnie 31–40). Omówimy dojrzewanie płuc dziecka, gromadzenie tkanki tłuszczowej oraz moment, w którym ciążę uznaje się za donoszoną (38. tydzień). To czas na pakowanie torby!",
    "stageId": "stage-02",
    "stageTitle": "Dwie kreski",
    "stageColor": "#15803d",
    "cloudflareUid": "a30f272e429d9e547c7bc2a897a06d7a",
    "durationSeconds": 94,
    "durationFormatted": "1:34",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/a30f272e429d9e547c7bc2a897a06d7a/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-04",
    "lessonNumber": 4,
    "filmNumber": 4,
    "title": "Wielka nowina – jak informować bliskich i świętować ciążę",
    "description": "Inspirująca rozmowa o emocjach towarzyszących poznaniu płci dziecka na USG i informowaniu rodziny. Dowiesz się, jak zorganizować Baby Shower i dlaczego warto uwiecznić ciążę na sesji zdjęciowej.",
    "stageId": "stage-02",
    "stageTitle": "Dwie kreski",
    "stageColor": "#15803d",
    "cloudflareUid": "6aec02ba767bce6ea354929bcac89125",
    "durationSeconds": 258,
    "durationFormatted": "4:18",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/6aec02ba767bce6ea354929bcac89125/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-05",
    "lessonNumber": 5,
    "filmNumber": 5,
    "title": "Cyfrowa pomoc i fakty – aplikacje ciążowe oraz mity",
    "description": "Sprawdzimy, jak aplikacje pomagają śledzić rozwój narządów dziecka dzień po dniu. Rozprawimy się też z popularnymi przesądami (np. o głaskaniu zwierząt czy straszeniu ciężarnej) i podpowiemy, jak zachować zdrowy rozsądek.",
    "stageId": "stage-02",
    "stageTitle": "Dwie kreski",
    "stageColor": "#15803d",
    "cloudflareUid": "43034b5685370ace27315ee26e3b6411",
    "durationSeconds": 256,
    "durationFormatted": "4:16",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/43034b5685370ace27315ee26e3b6411/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-06",
    "lessonNumber": 6,
    "filmNumber": 6,
    "title": "Szkoła rodzenia online – Twój bezpieczny i wygodny start",
    "description": "Dlaczego warto zacząć edukację już od 21. tygodnia ciąży? Poznasz zalety kursów online, szczególnie w czasach pandemii lub gdy masz zalecenie ograniczenia aktywności fizycznej.",
    "stageId": "stage-03",
    "stageTitle": "Wreszcie lepiej",
    "stageColor": "#b45309",
    "cloudflareUid": "ab0d90bf8a42fcf4d7e4debf10509f73",
    "durationSeconds": 259,
    "durationFormatted": "4:19",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/ab0d90bf8a42fcf4d7e4debf10509f73/thumbnails/thumbnail.jpg",
    "isFreePreview": true,
    "attachments": []
  },
  {
    "id": "lekcja-07",
    "lessonNumber": 7,
    "filmNumber": 7,
    "title": "Zmiany fizjologiczne w Twoim ciele – co jest normą?",
    "description": "Wyjaśnimy, dlaczego w ciąży rośnie objętość krwi (aż o 45%!), pojawiają się obrzęki, zgaga czy hemoroidy. Dowiesz się, jak hormony (estrogen i progesteron) wpływają na Twój wygląd i samopoczucie.",
    "stageId": "stage-03",
    "stageTitle": "Wreszcie lepiej",
    "stageColor": "#b45309",
    "cloudflareUid": "36090fe82c03944df21223b001113f98",
    "durationSeconds": 195,
    "durationFormatted": "3:15",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/36090fe82c03944df21223b001113f98/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-08",
    "lessonNumber": 8,
    "filmNumber": 8,
    "title": "Zmysły na wysokich obrotach – zmiana odczuwania zapachów",
    "description": "Czy zapach lodówki lub ulubionych perfum nagle stał się nie do zniesienia? Opowiemy o nadwrażliwości węchowej w I trymestrze i o tym, że na szczęście jest to stan przejściowy, który mija w II trymestrze.",
    "stageId": "stage-03",
    "stageTitle": "Wreszcie lepiej",
    "stageColor": "#b45309",
    "cloudflareUid": "0454963ecde1bee58fa12aa2b2f513ce",
    "durationSeconds": 134,
    "durationFormatted": "2:14",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/0454963ecde1bee58fa12aa2b2f513ce/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-09",
    "lessonNumber": 9,
    "filmNumber": 9,
    "title": "Dolegliwości ciążowe – jak sobie z nimi skutecznie radzić?",
    "description": "Szczera rozmowa o zmęczeniu i stresie. Nauczysz się odróżniać niegroźne objawy od cholestazy ciążowej (swędzenie dłoni) oraz rozpoznawać nieregularne skurcze przepowiadające, które przygotowują macicę do porodu.",
    "stageId": "stage-03",
    "stageTitle": "Wreszcie lepiej",
    "stageColor": "#b45309",
    "cloudflareUid": "80a3893c925771b809f87c39a6ddf8b6",
    "durationSeconds": 537,
    "durationFormatted": "8:57",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/80a3893c925771b809f87c39a6ddf8b6/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-10",
    "lessonNumber": 10,
    "filmNumber": 10,
    "title": "Higiena intymna w ciąży – profilaktyka infekcji",
    "description": "Poznasz zasady bezpiecznej pielęgnacji: jak się podmywać (kierunek ma znaczenie!), by uniknąć infekcji, dlaczego warto wybrać bawełnianą bieliznę i jak zmienia się pH pochwy w trakcie ciąży.",
    "stageId": "stage-03",
    "stageTitle": "Wreszcie lepiej",
    "stageColor": "#b45309",
    "cloudflareUid": "dc7311a22c7545a1aa5b4310e26a4dd3",
    "durationSeconds": 86,
    "durationFormatted": "1:26",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/dc7311a22c7545a1aa5b4310e26a4dd3/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-11",
    "lessonNumber": 11,
    "filmNumber": 11,
    "title": "Kalendarz badań w ciąży – Twoja kompletna checklista",
    "description": "Kompletny przegląd badań na każdą wizytę: od morfologii i USG, przez test obciążenia glukozą (24-28 tydzień), aż po kluczowy wymaz GBS, którego wynik musisz zabrać do szpitala.",
    "stageId": "stage-03",
    "stageTitle": "Wreszcie lepiej",
    "stageColor": "#b45309",
    "cloudflareUid": "9d3f5e1b9ee6826fe9d0a19d085d8b64",
    "durationSeconds": 469,
    "durationFormatted": "7:49",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/9d3f5e1b9ee6826fe9d0a19d085d8b64/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": [
      {
        "id": "att-11-1",
        "name": "Karta Pracy · Lekcja 11",
        "type": "pdf",
        "size": "1.4 MB"
      }
    ]
  },
  {
    "id": "lekcja-12",
    "lessonNumber": 12,
    "filmNumber": 51,
    "title": "Q&A z Położną – Sygnały alarmowe i kiedy jechać do szpitala",
    "description": "Kiedy krwawienie jest groźne? Co oznaczają „mroczki” przed oczami (nadciśnienie)? Położna wyjaśnia różnicę między sączeniem się wód płodowych a upławami i mówi, kiedy natychmiast jechać do szpitala.",
    "stageId": "stage-03",
    "stageTitle": "Wreszcie lepiej",
    "stageColor": "#b45309",
    "cloudflareUid": "eea7e6f75b1bab451f2f120e98d2c3ff",
    "durationSeconds": 376,
    "durationFormatted": "6:16",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/eea7e6f75b1bab451f2f120e98d2c3ff/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-13",
    "lessonNumber": 13,
    "filmNumber": 12,
    "title": "Ruchy dziecka i ułożenie – czego spodziewać się od 20. tygodnia?",
    "description": "Kiedy poczujesz pierwsze ruchy? Dominika opowiada o swoich doświadczeniach z „kopniakami” w 20. tygodniu oraz o stresie związanym z wynikami USG nerek płodu, który okazał się fałszywym alarmem.",
    "stageId": "stage-03",
    "stageTitle": "Wreszcie lepiej",
    "stageColor": "#b45309",
    "cloudflareUid": "7252fa19691fc33a9ff1c435a8eed5fe",
    "durationSeconds": 376,
    "durationFormatted": "6:16",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/7252fa19691fc33a9ff1c435a8eed5fe/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-14",
    "lessonNumber": 14,
    "filmNumber": 13,
    "title": "Zdrowy sen w ciąży – dobór materaca i mikroklimat sypialni",
    "description": "Jak dobrać średnio twardy materac i pościel do zmieniającej się sylwetki? Dowiesz się, dlaczego nawilżenie powietrza w sypialni (ok. 60%) i temperatura 18-21°C są kluczowe dla Ciebie i noworodka.",
    "stageId": "stage-03",
    "stageTitle": "Wreszcie lepiej",
    "stageColor": "#b45309",
    "cloudflareUid": "8e0f033cf50fd850258eed4f85b51743",
    "durationSeconds": 329,
    "durationFormatted": "5:29",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/8e0f033cf50fd850258eed4f85b51743/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-15",
    "lessonNumber": 15,
    "filmNumber": 14,
    "title": "Pozycje do snu i sposoby na bezsenność w ciąży",
    "description": "Dlaczego spanie na lewym boku jest najbezpieczniejszą opcją dla przepływu krwi i unikania ucisku na żyłę główną? Poznasz sposoby na bezsenność i częste nocne wizyty w toalecie.",
    "stageId": "stage-03",
    "stageTitle": "Wreszcie lepiej",
    "stageColor": "#b45309",
    "cloudflareUid": "9d80f3d86cccb3ec5faeaa1ba946fea0",
    "durationSeconds": 206,
    "durationFormatted": "3:26",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/9d80f3d86cccb3ec5faeaa1ba946fea0/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-16",
    "lessonNumber": 16,
    "filmNumber": 15,
    "title": "Fizjoterapia w ciąży – zestaw ćwiczeń na bóle kręgosłupa",
    "description": "Praktyczny instruktaż: nauka oddechu torem dolnożebrowym, mobilizacja miednicy na piłce („most”) i bezpieczne wzmacnianie pleców w klęku podpartym, by uniknąć bólu kręgosłupa.",
    "stageId": "stage-03",
    "stageTitle": "Wreszcie lepiej",
    "stageColor": "#b45309",
    "cloudflareUid": "4a219b5d8985a19b178518db924b9faa",
    "durationSeconds": 729,
    "durationFormatted": "12:09",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/4a219b5d8985a19b178518db924b9faa/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-17",
    "lessonNumber": 17,
    "filmNumber": 16,
    "title": "Odpoczynek, podróże i bezpieczna aktywność w ciąży",
    "description": "Czy w ciąży można jechać na wakacje? Rozmowa o bezpiecznym podróżowaniu samochodem (pasy pod brzuchem), odwiedzinach u rodziny na wsi i zachowaniu aktywności fizycznej do samego końca.",
    "stageId": "stage-03",
    "stageTitle": "Wreszcie lepiej",
    "stageColor": "#b45309",
    "cloudflareUid": "dae310a2b02ccf845d13197d5950cc59",
    "durationSeconds": 236,
    "durationFormatted": "3:56",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/dae310a2b02ccf845d13197d5950cc59/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-18",
    "lessonNumber": 18,
    "filmNumber": 17,
    "title": "Sprzątanie domu w ciąży – zasady bezpieczeństwa dla mamy",
    "description": "Czego unikać podczas domowych porządków? Wyjaśniamy, dlaczego nie wolno myć okien (unoszenie rąk grozi odklejeniem łożyska), sprzątać kociej kuwety (toksoplazmoza) i używać silnych detergentów w aerozolu.",
    "stageId": "stage-03",
    "stageTitle": "Wreszcie lepiej",
    "stageColor": "#b45309",
    "cloudflareUid": "e239f37b88abf2b75e3de1d871418312",
    "durationSeconds": 403,
    "durationFormatted": "6:43",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/e239f37b88abf2b75e3de1d871418312/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": [
      {
        "id": "att-18-1",
        "name": "Karta Pracy · Lekcja 18",
        "type": "pdf",
        "size": "1.4 MB"
      }
    ]
  },
  {
    "id": "lekcja-19",
    "lessonNumber": 19,
    "filmNumber": 18,
    "title": "Wózek i fotelik samochodowy – instruktaż obsługi i montażu",
    "description": "Zobacz, jak składać wózek jedną ręką, jak zamontować gondolę i – co najważniejsze – jak bezpiecznie zapiąć fotelik w samochodzie tyłem do kierunku jazdy (pasy lub baza Isofix).",
    "stageId": "stage-04",
    "stageTitle": "Torba spakowana",
    "stageColor": "#0369a1",
    "cloudflareUid": "569c3d62bd604913aee762e621fb04de",
    "durationSeconds": 430,
    "durationFormatted": "7:10",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/569c3d62bd604913aee762e621fb04de/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-20",
    "lessonNumber": 20,
    "filmNumber": 19,
    "title": "Jak wybrać idealny wózek dla dziecka? Praktyczne wskazówki",
    "description": "Na co zwrócić uwagę w sklepie: amortyzacja, rodzaj kół (pompowane na las vs piankowe na miasto) i waga stelaża. Porady rodziców, którzy wybrali polski model 3w1.",
    "stageId": "stage-04",
    "stageTitle": "Torba spakowana",
    "stageColor": "#0369a1",
    "cloudflareUid": "1e6a516e495831efed753fa92a8fd603",
    "durationSeconds": 524,
    "durationFormatted": "8:44",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/1e6a516e495831efed753fa92a8fd603/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-21",
    "lessonNumber": 21,
    "filmNumber": 20,
    "title": "Aranżacja pokoju dla dziecka – funkcjonalność i wygoda",
    "description": "Inspiracje na urządzenie kącika dla malucha. Dlaczego warto postawić na uniwersalne kolory (szarość, biel) i meble, które rosną razem z dzieckiem (np. łóżeczko-tapczanik 140x70).",
    "stageId": "stage-04",
    "stageTitle": "Torba spakowana",
    "stageColor": "#0369a1",
    "cloudflareUid": "bf8f08aba8a65f7ea8ff4254d956e504",
    "durationSeconds": 444,
    "durationFormatted": "7:24",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/bf8f08aba8a65f7ea8ff4254d956e504/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-22",
    "lessonNumber": 22,
    "filmNumber": 21,
    "title": "Bezpieczne łóżeczko – wybór materaca i profilaktyka SIDS",
    "description": "Twardy materac, wyjmowane szczebelki i brak zbędnych poduszek. Położna wyjaśnia, jak stworzyć bezpieczną strefę snu i dlaczego warto zrezygnować z ochraniaczy na rzecz śpiworków.",
    "stageId": "stage-04",
    "stageTitle": "Torba spakowana",
    "stageColor": "#0369a1",
    "cloudflareUid": "1a9c2975327e603d8081b6341943558f",
    "durationSeconds": 268,
    "durationFormatted": "4:28",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/1a9c2975327e603d8081b6341943558f/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-23",
    "lessonNumber": 23,
    "filmNumber": 22,
    "title": "Apteczka i kosmetyczka noworodka – co naprawdę warto kupić?",
    "description": "Lista zakupów „minimum”: witamina D3, paracetamol, sól fizjologiczna i Bepanthen. Dowiesz się, dlaczego woda i waciki to najlepsze kosmetyki na start, a Sudocrem zostawiamy na odparzenia.",
    "stageId": "stage-04",
    "stageTitle": "Torba spakowana",
    "stageColor": "#0369a1",
    "cloudflareUid": "475bb1e09e30cee402d4424e399f8ffb",
    "durationSeconds": 360,
    "durationFormatted": "6:00",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/475bb1e09e30cee402d4424e399f8ffb/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-24",
    "lessonNumber": 24,
    "filmNumber": 23,
    "title": "Kompletna wyprawka domowa – ubranka, tekstylia i akcesoria",
    "description": "Ile body i pajacyków kupić na start (min. 7 sztuk)? Checklista ubranek, kocyków, pieluch tetrowych i akcesoriów kąpielowych (ręcznik z kapturkiem) niezbędnych w pierwszych tygodniach.",
    "stageId": "stage-04",
    "stageTitle": "Torba spakowana",
    "stageColor": "#0369a1",
    "cloudflareUid": "05e122e50774f6f96d7416fd663a483c",
    "durationSeconds": 481,
    "durationFormatted": "8:01",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/05e122e50774f6f96d7416fd663a483c/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-25",
    "lessonNumber": 25,
    "filmNumber": 40,
    "title": "Wanienka do kąpieli – przegląd modeli i praktyczne porady",
    "description": "Przegląd dostępnych modeli: wanienki ze stelażem, składane (podróżne) oraz te z wbudowanym termometrem. Podpowiadamy, dlaczego warto mieć dwa egzemplarze, jeśli często odwiedzasz dziadków.",
    "stageId": "stage-04",
    "stageTitle": "Torba spakowana",
    "stageColor": "#0369a1",
    "cloudflareUid": "1c235b5735ca98f4d73cec632fe2b4af",
    "durationSeconds": 119,
    "durationFormatted": "1:59",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/1c235b5735ca98f4d73cec632fe2b4af/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": [
      {
        "id": "att-25-1",
        "name": "Karta Pracy · Lekcja 25",
        "type": "pdf",
        "size": "1.4 MB"
      }
    ]
  },
  {
    "id": "lekcja-26",
    "lessonNumber": 26,
    "filmNumber": 25,
    "title": "Plan Porodu krok po kroku – jak przygotować dokument?",
    "description": "Wspólnie omówimy każdy punkt planu porodu: od zgody na obecność studentów, przez nacięcie krocza, aż po kontakt „skóra do skóry” (2h) i pierwsze karmienie.",
    "stageId": "stage-05",
    "stageTitle": "Zaczęło się",
    "stageColor": "#EC008C",
    "cloudflareUid": "ea898b3a4f5e4b7e23d212d595b13f47",
    "durationSeconds": 639,
    "durationFormatted": "10:39",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/ea898b3a4f5e4b7e23d212d595b13f47/thumbnails/thumbnail.jpg",
    "isFreePreview": true,
    "attachments": [
      {
        "id": "att-26-1",
        "name": "Karta Pracy · Lekcja 26",
        "type": "pdf",
        "size": "1.4 MB"
      }
    ]
  },
  {
    "id": "lekcja-27",
    "lessonNumber": 27,
    "filmNumber": 26,
    "title": "Torba do szpitala – pakowanie w 3 krokach",
    "description": "Podzielimy Twój bagaż na trzy strefy: rzeczy na porodówkę (pomadka, woda), na oddział dla Mamy (koszule, podkłady) i dla Dziecka (pieluszki, chusteczki).",
    "stageId": "stage-05",
    "stageTitle": "Zaczęło się",
    "stageColor": "#EC008C",
    "cloudflareUid": "1f6c80e6f0051eb884e19a7bb6b81803",
    "durationSeconds": 168,
    "durationFormatted": "2:48",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/1f6c80e6f0051eb884e19a7bb6b81803/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-28",
    "lessonNumber": 28,
    "filmNumber": 27,
    "title": "Rodzaje porodów – poród naturalny, cesarskie cięcie i poród zabiegowy",
    "description": "Czym różni się poród naturalny od cięcia cesarskiego (planowego i nagłego)? Dowiesz się także, na czym polega poród zabiegowy (kleszcze, vacuum) i kiedy się go stosuje.",
    "stageId": "stage-05",
    "stageTitle": "Zaczęło się",
    "stageColor": "#EC008C",
    "cloudflareUid": "1b5195ea3b2bb8f207e8b1dddec8ce71",
    "durationSeconds": 414,
    "durationFormatted": "6:54",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/1b5195ea3b2bb8f207e8b1dddec8ce71/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-29",
    "lessonNumber": 29,
    "filmNumber": 28,
    "title": "Gdy wody odejdą – instrukcja postępowania w dniu porodu",
    "description": "Instrukcja postępowania w pierwszej fazie porodu. Kiedy wziąć prysznic, wykonać \"chód bociana\", zjeść lekki posiłek i w którym momencie (skurcze co 5 minut) ruszyć do szpitala.",
    "stageId": "stage-05",
    "stageTitle": "Zaczęło się",
    "stageColor": "#EC008C",
    "cloudflareUid": "4d8681e85878c30e0ea33e7811a2e405",
    "durationSeconds": 140,
    "durationFormatted": "2:20",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/4d8681e85878c30e0ea33e7811a2e405/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-30",
    "lessonNumber": 30,
    "filmNumber": 29,
    "title": "Aktywny poród – niefarmakologiczne metody łagodzenia bólu",
    "description": "Jak wykorzystać ruch, by zmniejszyć ból? Poznasz pozycje wertykalne (kuczna, worki sako), techniki masażu krzyża oraz sposoby na relaksację pod prysznicem.",
    "stageId": "stage-05",
    "stageTitle": "Zaczęło się",
    "stageColor": "#EC008C",
    "cloudflareUid": "008e24bd7f5fc89e74ffeacb60f6ebe2",
    "durationSeconds": 442,
    "durationFormatted": "7:22",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/008e24bd7f5fc89e74ffeacb60f6ebe2/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-31",
    "lessonNumber": 31,
    "filmNumber": 30,
    "title": "Fizjoterapia na porodówce – pozycje i ćwiczenia z partnerem",
    "description": "Ćwiczenia na piłce (krążenia miednicą), niski przysiad z partnerem (Malasana) i otwieranie bioder – techniki, które ułatwiają dziecku wstawienie się w kanał rodny.",
    "stageId": "stage-05",
    "stageTitle": "Zaczęło się",
    "stageColor": "#EC008C",
    "cloudflareUid": "6be2c4a21f49b7c6ccc59a0f1946acaa",
    "durationSeconds": 297,
    "durationFormatted": "4:57",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/6be2c4a21f49b7c6ccc59a0f1946acaa/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-32",
    "lessonNumber": 32,
    "filmNumber": 31,
    "title": "Wykorzystanie chusty (Rebozo) do łagodzenia bólów porodowych",
    "description": "Zobacz, jak partner może użyć chusty, aby odciążyć Twój brzuch w pozycji kolankowo-łokciowej i zniwelować bóle lędźwiowe w trakcie skurczów.",
    "stageId": "stage-06",
    "stageTitle": "Plan B",
    "stageColor": "#7e22ce",
    "cloudflareUid": "de4eedf477e58dc60ebd9f1061e13994",
    "durationSeconds": 127,
    "durationFormatted": "2:07",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/de4eedf477e58dc60ebd9f1061e13994/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-33",
    "lessonNumber": 33,
    "filmNumber": 32,
    "title": "Farmakologiczne metody łagodzenia bólu – gaz, ZZO i leki rozkurczowe",
    "description": "Wszystko o znieczuleniu: jak działa gaz rozweselający, leki rozkurczowe (Nalpain) oraz kiedy można podać znieczulenie zewnątrzoponowe (między 4 a 5 cm rozwarcia).",
    "stageId": "stage-06",
    "stageTitle": "Plan B",
    "stageColor": "#7e22ce",
    "cloudflareUid": "1d6ccdc8860f1a9a4459d1d07391550d",
    "durationSeconds": 540,
    "durationFormatted": "9:00",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/1d6ccdc8860f1a9a4459d1d07391550d/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-34",
    "lessonNumber": 34,
    "filmNumber": 33,
    "title": "Cztery okresy porodu – przewodnik po etapach narodzin",
    "description": "Szczegółowy opis czterech okresów porodu: od rozwierania szyjki (i kryzysu 7. centymetra), przez parcie, aż po rodzenie łożyska i dwugodzinną obserwację poporodową.",
    "stageId": "stage-06",
    "stageTitle": "Plan B",
    "stageColor": "#7e22ce",
    "cloudflareUid": "0867a820fde9b11b8d5499700bee8e71",
    "durationSeconds": 476,
    "durationFormatted": "7:56",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/0867a820fde9b11b8d5499700bee8e71/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-35",
    "lessonNumber": 35,
    "filmNumber": 37,
    "title": "Pielęgnacja rany po cięciu cesarskim i nacięciu krocza",
    "description": "Kluczowe zasady gojenia: wietrzenie krocza (leżenie bez bielizny), mycie rany po cc szarym mydłem i późniejsza mobilizacja blizny, by uniknąć zrostów.",
    "stageId": "stage-07",
    "stageTitle": "Pierwsza noc w domu",
    "stageColor": "#be185d",
    "cloudflareUid": "640176e052d62d597475cad4205794d1",
    "durationSeconds": 129,
    "durationFormatted": "2:09",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/640176e052d62d597475cad4205794d1/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-36",
    "lessonNumber": 36,
    "filmNumber": 38,
    "title": "Fizjologia połogu – odchody połogowe, płodność i Baby Blues",
    "description": "Czego spodziewać się po powrocie do domu? Omówienie odchodów połogowych, powrotu płodności (nawet przy karmieniu piersią!) oraz emocjonalnego „Baby Blues” do 10. doby.",
    "stageId": "stage-07",
    "stageTitle": "Pierwsza noc w domu",
    "stageColor": "#be185d",
    "cloudflareUid": "080ceb2cab9bca47481293fc3f64b176",
    "durationSeconds": 196,
    "durationFormatted": "3:16",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/080ceb2cab9bca47481293fc3f64b176/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-37",
    "lessonNumber": 37,
    "filmNumber": 46,
    "title": "Fizjoterapia po porodzie – bezpieczne ćwiczenia brzucha i dna miednicy",
    "description": "Bezpieczne ćwiczenia na start (ok. 5-6 tyg. po porodzie): aktywacja mięśnia poprzecznego brzucha z piłką softball. Dowiesz się, dlaczego absolutnie nie wolno robić „brzuszków”.",
    "stageId": "stage-07",
    "stageTitle": "Pierwsza noc w domu",
    "stageColor": "#be185d",
    "cloudflareUid": "464903222d97db10e975dd97a49c5a7d",
    "durationSeconds": 336,
    "durationFormatted": "5:36",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/464903222d97db10e975dd97a49c5a7d/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-38",
    "lessonNumber": 38,
    "filmNumber": 52,
    "title": "Wywiad po porodzie – historia Ani o cesarskim cięciu i powrocie do sprawności",
    "description": "Inspirująca opowieść mamy po cesarskim cięciu. Jak wyglądał jej szybki powrót do sprawności (prysznic po 12h), karmienie piersią i dlaczego wsparcie partnera było kluczowe.",
    "stageId": "stage-07",
    "stageTitle": "Pierwsza noc w domu",
    "stageColor": "#be185d",
    "cloudflareUid": "bead8f3f16b41c0aa611df30526ce6db",
    "durationSeconds": 650,
    "durationFormatted": "10:50",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/bead8f3f16b41c0aa611df30526ce6db/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-39",
    "lessonNumber": 39,
    "filmNumber": 53,
    "title": "Wywiad po porodzie – historia Karoliny o porodzie wywoływanym i regeneracji",
    "description": "Szczera rozmowa o porodzie wywoływanym (balonik, oksytocyna) zakończonym cc. Dowiesz się, jak mata edukacyjna może uratować chwilę dla mamy w pierwszych miesiącach.",
    "stageId": "stage-07",
    "stageTitle": "Pierwsza noc w domu",
    "stageColor": "#be185d",
    "cloudflareUid": "d2006cbad7d2c6ed190577b49e645285",
    "durationSeconds": 590,
    "durationFormatted": "9:50",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/d2006cbad7d2c6ed190577b49e645285/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": [
      {
        "id": "att-39-1",
        "name": "Karta Pracy · Lekcja 39",
        "type": "pdf",
        "size": "1.4 MB"
      }
    ]
  },
  {
    "id": "lekcja-40",
    "lessonNumber": 40,
    "filmNumber": 34,
    "title": "Wygląd noworodka po porodzie – skala Apgar i pierwsze chwile",
    "description": "Dlaczego główka może być stożkowata, oczy opuchnięte, a rączki sine? Wyjaśniamy, czym jest skala Apgar, maź płodowa (nie zmywamy jej przez 24h!) i ciemiączko.",
    "stageId": "stage-09",
    "stageTitle": "Nie śpi",
    "stageColor": "#4338ca",
    "cloudflareUid": "21baa2cafef2f7731b4a36c6464ee6e8",
    "durationSeconds": 148,
    "durationFormatted": "2:28",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/21baa2cafef2f7731b4a36c6464ee6e8/thumbnails/thumbnail.jpg",
    "isFreePreview": true,
    "attachments": []
  },
  {
    "id": "lekcja-41",
    "lessonNumber": 41,
    "filmNumber": 35,
    "title": "Zachowania i odruchy noworodka – co jest normą fizjologiczną?",
    "description": "Kichanie, czkawka i drżenie bródki – co jest normą? Zobaczysz, jak wygląda odruch Moro (rozrzucenie rączek) i dlaczego nie należy się go bać.",
    "stageId": "stage-09",
    "stageTitle": "Nie śpi",
    "stageColor": "#4338ca",
    "cloudflareUid": "5ea98f36b8adf89a1e3c9a670e317026",
    "durationSeconds": 191,
    "durationFormatted": "3:11",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/5ea98f36b8adf89a1e3c9a670e317026/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": [
      {
        "id": "att-41-1",
        "name": "Karta Pracy · Lekcja 41",
        "type": "pdf",
        "size": "1.4 MB"
      }
    ]
  },
  {
    "id": "lekcja-42",
    "lessonNumber": 42,
    "filmNumber": 36,
    "title": "Zasady profilaktyki śmierci łóżeczkowej (SIDS)",
    "description": "Złote zasady bezpiecznego snu: twardy materac, pozycja wyłącznie na plecach i brak kołderek oraz ochraniaczy w łóżeczku.",
    "stageId": "stage-09",
    "stageTitle": "Nie śpi",
    "stageColor": "#4338ca",
    "cloudflareUid": "fe6729ee7d0ba57ec0717bc04dc5f32b",
    "durationSeconds": 58,
    "durationFormatted": "0:58",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/fe6729ee7d0ba57ec0717bc04dc5f32b/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-43",
    "lessonNumber": 43,
    "filmNumber": 39,
    "title": "Pierwsza pomoc noworodkowa (RKO) – instruktaż ratowania życia",
    "description": "Instruktaż ratowania życia noworodka, gdy przestanie oddychać. Nauczysz się schematu: 5 oddechów ratunkowych i 30 uciśnięć klatki piersiowej.",
    "stageId": "stage-09",
    "stageTitle": "Nie śpi",
    "stageColor": "#4338ca",
    "cloudflareUid": "a4d347d5cd2b18cad5c1dcbade6d5598",
    "durationSeconds": 154,
    "durationFormatted": "2:34",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/a4d347d5cd2b18cad5c1dcbade6d5598/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-44",
    "lessonNumber": 44,
    "filmNumber": 41,
    "title": "Kąpiel i pielęgnacja noworodka krok po kroku",
    "description": "Praktyczny pokaz kąpieli: temperatura wody (37-38°C), bezpieczny chwyt, mycie oczu, noska (aspirator) i pielęgnacja kikuta pępowinowego „na sucho”.",
    "stageId": "stage-09",
    "stageTitle": "Nie śpi",
    "stageColor": "#4338ca",
    "cloudflareUid": "da9e1a2801f8e9469fccbdd2b9d8a67d",
    "durationSeconds": 793,
    "durationFormatted": "13:13",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/da9e1a2801f8e9469fccbdd2b9d8a67d/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-45",
    "lessonNumber": 45,
    "filmNumber": 47,
    "title": "Szczepienia ochronne dziecka – kalendarz i przygotowanie do wizyty",
    "description": "Przewodnik po kalendarzu szczepień (obowiązkowe i zalecane). Kiedy odbywa się pierwsze szczepienie (gruźlica, WZW B w 1. dobie) i czym różnią się szczepionki 5w1/6w1.",
    "stageId": "stage-09",
    "stageTitle": "Nie śpi",
    "stageColor": "#4338ca",
    "cloudflareUid": "6abd5545230ca985f3461ce88cac3c7e",
    "durationSeconds": 372,
    "durationFormatted": "6:12",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/6abd5545230ca985f3461ce88cac3c7e/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-46",
    "lessonNumber": 46,
    "filmNumber": 48,
    "title": "Stany przejściowe noworodka – żółtaczka, spadek wagi i rumień",
    "description": "Żółtaczka fizjologiczna (fototerapia), fizjologiczny spadek wagi (do 10%) i rumień. Wyjaśniamy też „odczyny ciążowe” (powiększone gruczoły piersiowe), które są efektem hormonów mamy.",
    "stageId": "stage-09",
    "stageTitle": "Nie śpi",
    "stageColor": "#4338ca",
    "cloudflareUid": "2e6438b0eb0336b69f8dbc2b8bfdf3cc",
    "durationSeconds": 277,
    "durationFormatted": "4:37",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/2e6438b0eb0336b69f8dbc2b8bfdf3cc/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-47",
    "lessonNumber": 47,
    "filmNumber": 49,
    "title": "Typowe problemy noworodkowe – ulewanie, ciemieniucha i potówki",
    "description": "Co robić, gdy dziecko ulewa (pionizacja), ma potówki (nie przegrzewać!) lub ciemieniuchę (oliwka i wyczesywanie)? Poznasz domowe sposoby na pielęgnację.",
    "stageId": "stage-09",
    "stageTitle": "Nie śpi",
    "stageColor": "#4338ca",
    "cloudflareUid": "1e112867f1ffa8f506114ae738b3d931",
    "durationSeconds": 244,
    "durationFormatted": "4:04",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/1e112867f1ffa8f506114ae738b3d931/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-48",
    "lessonNumber": 48,
    "filmNumber": 50,
    "title": "Q&A z Położną – Odpowiedzi na pytania o pielęgnację noworodka",
    "description": "Odpowiedzi na najczęstsze pytania: trądzik niemowlęcy, żółta kupka, bąbelek na ustach od ssania i pierwszy spacer.",
    "stageId": "stage-09",
    "stageTitle": "Nie śpi",
    "stageColor": "#4338ca",
    "cloudflareUid": "9ab1c67287a8c756d5288e515d8dcca3",
    "durationSeconds": 411,
    "durationFormatted": "6:51",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/9ab1c67287a8c756d5288e515d8dcca3/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-49",
    "lessonNumber": 49,
    "filmNumber": 42,
    "title": "Pozycje do karmienia piersią – technika i prawidłowy chwyt",
    "description": "Nauczysz się przystawiać dziecko w pozycji klasycznej, krzyżowej (dla początkujących) i spod pachy (idealnej po cesarce). Dowiesz się, jak sprawdzić, czy dziecko efektywnie ssie.",
    "stageId": "stage-08",
    "stageTitle": "Karmienie",
    "stageColor": "#0e7490",
    "cloudflareUid": "b7b2bd16c73c8386d92746e1e85337ba",
    "durationSeconds": 349,
    "durationFormatted": "5:49",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/b7b2bd16c73c8386d92746e1e85337ba/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": [
      {
        "id": "att-49-1",
        "name": "Karta Pracy · Lekcja 49",
        "type": "pdf",
        "size": "1.4 MB"
      }
    ]
  },
  {
    "id": "lekcja-50",
    "lessonNumber": 50,
    "filmNumber": 43,
    "title": "Problemy laktacyjne – nawał pokarmowy, zastoje i bolesne brodawki",
    "description": "Nawał pokarmowy (okłady ciepłe/zimne), zastój i bolesne brodawki – sprawdzone sposoby na ulgę i utrzymanie laktacji na żądanie.",
    "stageId": "stage-08",
    "stageTitle": "Karmienie",
    "stageColor": "#0e7490",
    "cloudflareUid": "2cbde448f7f7100d2f869d82c0f4b0f9",
    "durationSeconds": 218,
    "durationFormatted": "3:38",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/2cbde448f7f7100d2f869d82c0f4b0f9/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-51",
    "lessonNumber": 51,
    "filmNumber": 44,
    "title": "Akcesoria do karmienia – laktatory, butelki i kolektory pokarmu",
    "description": "Przegląd laktatorów dwufazowych, butelek antykolkowych, muszli laktacyjnych i kolektorów pokarmu. Jak dobrać stanik i kiedy stosować kapturki na brodawki?",
    "stageId": "stage-08",
    "stageTitle": "Karmienie",
    "stageColor": "#0e7490",
    "cloudflareUid": "9d7b561b50b1e4ade2e31a1323b2b4af",
    "durationSeconds": 286,
    "durationFormatted": "4:46",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/9d7b561b50b1e4ade2e31a1323b2b4af/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  },
  {
    "id": "lekcja-52",
    "lessonNumber": 52,
    "filmNumber": 45,
    "title": "Kolki niemowlęce – przyczyny, masaż i sposoby na ulgę",
    "description": "Jak odróżnić kolkę od zwykłego płaczu (wieczorne godziny)? Metody łagodzenia bólu brzuszka: masaż, termofor z pestek wiśni, szumisie i probiotyki.",
    "stageId": "stage-08",
    "stageTitle": "Karmienie",
    "stageColor": "#0e7490",
    "cloudflareUid": "55e54d728445b43328229705b0ca141a",
    "durationSeconds": 587,
    "durationFormatted": "9:47",
    "thumbnailUrl": "https://customer-6d9sm694eja9tkvc.cloudflarestream.com/55e54d728445b43328229705b0ca141a/thumbnails/thumbnail.jpg",
    "isFreePreview": false,
    "attachments": []
  }
];

export const medicineCabinetItems: MedicineCabinetItem[] = [
  {
    id: "med-1",
    tag: "Mdłości i zgaga",
    title: "Sposoby na poranne mdłości i refluks",
    category: "Ciąża · Objawy",
    stageId: "stage-02",
    lessonId: "lekcja-01",
    previewText: "Częste małe posiłki, woda z imbirem, unikanie leżenia po jedzeniu i bezpieczne nawyki."
  },
  {
    id: "med-2",
    tag: "Badania i USG",
    title: "Kalendarz badań w ciąży i wymaz GBS",
    category: "Zdrowie · Profilaktyka",
    stageId: "stage-03",
    lessonId: "lekcja-11",
    previewText: "Checklista badań od morfologii po test glukozy i kluczowy wymaz GBS przed porodem."
  },
  {
    id: "med-3",
    tag: "Ból pleców",
    title: "Zestaw ćwiczeń na kręgosłup i oddech",
    category: "Fizjoterapia",
    stageId: "stage-03",
    lessonId: "lekcja-15",
    previewText: "Mobilizacja miednicy na piłce, bezpieczny klęk podparty i oddech torem dolnożebrowym."
  },
  {
    id: "med-4",
    tag: "Wyprawka szpitalna",
    title: "Torba do szpitala w 3 strefach",
    category: "Przygotowanie",
    stageId: "stage-05",
    lessonId: "lekcja-27",
    previewText: "Podział bagażu: strefa porodu, oddział położniczy dla Mamy oraz wyprawka dla Noworodka."
  },
  {
    id: "med-5",
    tag: "Odejście wód",
    title: "Gdy wody odejdą – co robić krok po kroku",
    category: "Poród · Start",
    stageId: "stage-05",
    lessonId: "lekcja-29",
    previewText: "Ocena koloru wód, prysznic, chód bociana i zasada 5-1-1 przed wyjazdem na izbę przyjęć."
  },
  {
    id: "med-6",
    tag: "Łagodzenie bólu",
    title: "Pozycje wertykalne i masaż krzyża",
    category: "Poród · Niefarmakologiczne",
    stageId: "stage-05",
    lessonId: "lekcja-30",
    previewText: "Ruch ułatwiający wstawianie główki, worki sako, chusta Rebozo i rola partnera."
  },
  {
    id: "med-7",
    tag: "Znieczulenie ZZO",
    title: "Farmakologia: gaz, leki rozkurczowe i zewnątrzoponowe",
    category: "Poród · Medycyna",
    stageId: "stage-06",
    lessonId: "lekcja-33",
    previewText: "Kiedy podaje się ZZO (4-5 cm), jak działa gaz rozweselający i jakie są wskazania."
  },
  {
    id: "med-8",
    tag: "Rana po cesarce / nacięciu",
    title: "Pielęgnacja rany po cc i krocza",
    category: "Połóg · Regeneracja",
    stageId: "stage-07",
    lessonId: "lekcja-35",
    previewText: "Wietrzenie rany, mycie szarym mydłem, unikanie podrażnień i mobilizacja blizny."
  },
  {
    id: "med-9",
    tag: "Karmienie piersią",
    title: "Prawidłowy chwyt i pozycje karmienia",
    category: "Laktacja",
    stageId: "stage-08",
    lessonId: "lekcja-49",
    previewText: "Chwyt asymetryczny brodawki, pozycja spod pachy po cięciu cesarskim i nawał."
  },
  {
    id: "med-10",
    tag: "Kolki niemowlęce",
    title: "Masaż brzuszka i ulga w kolce",
    category: "Noworodek · Dolegliwości",
    stageId: "stage-08",
    lessonId: "lekcja-52",
    previewText: "Prawidłowa technika masażu, termofor z pestek wiśni, pionizacja i spokój rodzica."
  },
  {
    id: "med-11",
    tag: "Pierwsza pomoc RKO",
    title: "Resuscytacja noworodka i zadławienia",
    category: "Bezpieczeństwo · SOS",
    stageId: "stage-09",
    lessonId: "lekcja-43",
    previewText: "Instruktaż ratowania życia: 5 oddechów ratowniczych, 30 uciśnięć dwoma palcami."
  },
  {
    id: "med-12",
    tag: "Kąpiel i pępek",
    title: "Pierwsza kąpiel i pielęgnacja kikuta",
    category: "Pielęgnacja",
    stageId: "stage-09",
    lessonId: "lekcja-44",
    previewText: "Temperatura wody 37°C, pewny chwyt, pielęgnacja pępka na sucho bez alkoholu."
  }
];

export function getLessonById(id: string): Lesson | undefined {
  return lessons.find((l) => l.id === id || l.lessonNumber === parseInt(id, 10));
}

export function getStageById(stageId: string): Stage | undefined {
  return stages.find((s) => s.id === stageId || s.slug === stageId);
}

export function getLessonsByStage(stageId: string): Lesson[] {
  return lessons.filter((l) => l.stageId === stageId);
}

export function getAdjacentLessons(lessonId: string): { prev?: Lesson; next?: Lesson } {
  const idx = lessons.findIndex((l) => l.id === lessonId);
  if (idx === -1) return {};
  return {
    prev: idx > 0 ? lessons[idx - 1] : undefined,
    next: idx < lessons.length - 1 ? lessons[idx + 1] : undefined,
  };
}
